HMS-2693 feat: Implement JWK creation and load
podengo-project/idmsvc-backend pull request #14
Opened 2023-10-04 12:46 UTC by tiran

Implement functions to create a new JWK with expected properties and load a serialized JWK.

`GenericePrivateJWK()` creates a private JWK with EC / P256, kid, and expiration time stamp.

`GetPublicJWK()` is a helper to create a public JWK from a private JWK.

`ParseJWK()` deserializes a JWK string that has been previously serialized with `json.Marshal`. The function validates various properties including expiration.

2023-10-05 06:22 UTC, tiran commented
I have modified `GenericePrivateJWK()` to take an expiration time instead of a validity time duration. It makes it easier to test the code and later to store the expiration time in the database.

2023-10-05 12:58 UTC, frasertweedale commented on internal/infrastructure/token/jwk.go
> +func GenericePrivateJWK(expiration time.Time) (jwk.Key, error) {
nit: typo, Generice -> Generate

2023-10-05 13:01 UTC, frasertweedale requested changes
One nit.  Apart from that, I'm happy with the PR and feel free to merge.

2023-10-06 01:35 UTC, frasertweedale commented
Thanks!  Merging.

2023-10-06 01:36 UTC, frasertweedale approved these changes

2023-10-06 01:37 UTC, merged