doc(HMS-3527): add rbac dev documentation
podengo-project/idmsvc-backend pull request #180
Opened 2024-04-03 18:05 UTC by avisiedo

Update developer documentation adding a new rbac section to the development documentation.

2024-04-04 05:29 UTC, tiran requested changes
Could you please explain briefly, how each permission influences idmsvc-backend. How does access as `super-admin` behave differently than `domain-admin`?

2024-04-04 05:29 UTC, tiran commented on docs/dev/08-rbac.md
> +- `domain-admin`: contain the default Domain Admin permissions.
```suggestion
- `domain-admin` (default): contain the default Domain Admin permissions.
```

2024-04-04 05:29 UTC, tiran commented on docs/dev/08-rbac.md
> +```
```suggestion
- Start with a different profile: `make mock-rbac-up APP_CLIENTS_RBAC_PROFILE=domain-readonly`
```

2024-04-04 14:22 UTC, avisiedo commented
> Could you please explain briefly, how each permission influences idmsvc-backend. How does access as `super-admin` behave differently than `domain-admin`?

Sure! `super-admin` is using wildcards, meanwhile `super-admin` is providing the whole set of permissions that our service manage.

In terms of behavior of our service, both profiles must behave in the same way! the existence of the `super-admin` profile is to have evidences on our tests (or some bug replayed on the future) that our service is managing correctly the wildcards when checking a required permissions against the ACL list returned from the rbac microservice.

2024-04-26 18:36 UTC, avisiedo commented
> Could you please explain briefly, how each permission influences idmsvc-backend. How does access as `super-admin` behave differently than `domain-admin`?

Sorry! I thought about this as a clarification on the comments of the PR instead of the content of the documentation. I have updated the content.

2024-05-23 14:36 UTC, frasertweedale approved these changes

2024-05-23 14:36 UTC, merged