fix: use different Pendo API keys base on endpoint
podengo-project/idmsvc-backend pull request #311
Opened 2024-08-30 13:52 UTC by pvoborni

Track Events and Metadata have slightly different endpoint URLs and also they use different API keys.

This change introduces the new config value for the track event key and changes the URLs.

Also now the base URL is expected to be e.g.: `https://app.pendo.io`.

Related to HMS-4503

2024-09-05 09:48 UTC, avisiedo requested changes
Thanks for the change!

- I have added a couple of notes.
- I have reviewed the paths with the API and they are ok:
  - https://engageapi.pendo.io/?bash%23#e45be48e-e01f-4f0a-acaa-73ef6851c4ac
  - https://engageapi.pendo.io/?bash%23#bd14400e-0ff9-49e6-932e-61e7a65c6f3c

2024-09-05 09:59 UTC, pvoborni commented on internal/config/config.go
> +	v.SetDefault("clients.pendo_track_event_key", "")
I think on Friday we discussed to make the clowder config based on this PR.

2024-09-08 21:36 UTC, avisiedo commented on internal/config/config.go
> +	PendoTrackEventKey string `mapstructure:"pendo_track_event_key" json:"-"`
nevermind! I forgot about previous agreement!

2024-09-08 21:36 UTC, avisiedo commented on internal/config/config.go
> +	v.SetDefault("clients.pendo_track_event_key", "")
right! I forgot about it! sorry!

2024-09-08 21:44 UTC, avisiedo approved these changes
LGTM

2024-09-09 07:09 UTC, merged