fix: typo "deletet_at" > "deleted_at"
podengo-project/idmsvc-backend pull request #452
Opened 2024-12-18 14:18 UTC by avisiedo

The change does not modify or impact anything, but make the definition aligned
according with the implementation.

2024-12-18 22:06 UTC, frasertweedale requested changes
The typo also appears in `docs/dev/TESTING.md` (2 occurrences).  It should be corrected there too.

Apart from that, ACK.

2024-12-19 22:52 UTC, frasertweedale commented
`docs/dev/TESTING.md` is still missing the update?

2025-01-06 00:38 UTC, frasertweedale commented
ping @avisiedo ^^^.  I can't force-push to update this PR, due to your security settings.  So, could you please update `docs/dev/TESTING.md`?  Otherwise, I can create a new PR to supersede this one.  Cheers!

2025-01-07 10:28 UTC, avisiedo commented
@frasertweedale ; I have rebased, in a previous pr several changes are applied to `docs/dev/TESTING.md` file, so they remove the need to update that file; commit [`159566f`.](https://github.com/podengo-project/idmsvc-backend/commit/159566f854e57f345a473739ec336d0db68b83ab)

Let me know if further changes are necessary; thanks mate!

2025-01-09 00:55 UTC, frasertweedale approved these changes

2025-01-09 00:56 UTC, merged